=== Nyanna/XY.JCms/src/main/resources/dtd/usecases-10116.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 *  This file is part of XY.JCms, Copyright 2010 (C) Xyan Kruse, Xyan@gmx.net, Xyan.kilu.de
 *
 *  XY.JCms is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  XY.JCms is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with XY.JCms.  If not, see <http://www.gnu.org/licenses/>.
 */
 -->
 <!ELEMENT usecases (usecase)*>
 
 <!ELEMENT usecase (description , (parameter | controller | configurations)*)>
 
 <!ATTLIST usecase
 	id		CDATA		#REQUIRED
>
 
 <!ELEMENT description (#PCDATA)>
 
 <!ELEMENT parameter (param)*>
 
 <!ELEMENT param EMPTY>
 
 <!ATTLIST param
 	key			CDATA		#REQUIRED
 	valueType	CDATA		#REQUIRED
>

<!ELEMENT controller (class)*>

<!ELEMENT class EMPTY>

<!ATTLIST class
	path				CDATA		#REQUIRED
	obmitConfig	CDATA		#IMPLIED
>

<!ELEMENT configurations (configuration)*>

<!ELEMENT configuration (#PCDATA)>

<!ATTLIST configuration
	type		CDATA		#REQUIRED
	include	CDATA		#IMPLIED
>

=== Nyanna/XY.JCms/src/test/resources/net/xy/jcms/ExampleUsecases.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE usecases PUBLIC "http://jcms.xy.net/UsecaseConfiguration-1.0.dtd" "usecases-10116.dtd">
<!--
/**
 *  This file is part of XY.JCms, Copyright 2010 (C) Xyan Kruse, Xyan@gmx.net, Xyan.kilu.de
 *
 *  XY.JCms is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  XY.JCms is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with XY.JCms.  If not, see <http://www.gnu.org/licenses/>.
 */
 -->
<usecases>
    <usecase id="subcategory" >
    	<description> sld ead asd alksdas dliasudish ad asd asuzd uas ukdza sdzas dkuuas dzsaukdz  ku</description>
        <parameter>
            <param key="catalogid" valueType="java.lang.Integer"/>
        </parameter>

        <configurations>
        	<configuration type="TemplateConfiguration" include="class://de.jj.fragmentspool.subcategoryPage"/>
        </configurations>
    </usecase>

    <usecase id="userLogin" >
    	<description> sld ead asd alksdas dliasudish ad asd asuzd uas ukdza sdzas dkuuas dzsaukdz  ku</description>
        <parameter>
            <param key="lvp" valueType="net.xyan.NavigationAbstractionLayer.NALKeyList"/>
        </parameter>

        <controller>
            <!-- Controller fill the ControllerConfiguration in case of login errors or directs to lvp-->
            <class path="net.xyan.controller.UserController" obmitConfig="Parameters"/>
        </controller>

        <configurations>
	        <configuration type="TemplateConfiguration" include="class://de.jj.fragmentspool.myarea.loginPage"/>
        </configurations>
    </usecase>
    
    <usecase id="contentgroup">
    	<description> sld ead asd alksdas dliasudish ad asd asuzd uas ukdza sdzas dkuuas dzsaukdz  ku</description>
        <parameter>
            <!-- All these parameters are mendatory and will be validated. Usecase recognizion can be based on the most matching parameters count-->
            <param key="contentgroup" valueType="de.jamba.ContentGroup"/>
        </parameter>

        <controller>
            <!-- checks if an login is needed and performs an usecase redirect with lvp parameter which is the actual NALKeyList-->
            <class path="net.xyan.controller.UserController"/>
            <!-- Controller maybe redirects to an content not supported usecase -->
            <class path="net.xyan.controller.ClientSupportsContentController" obmitConfig="ContentConfiguration,Parameters"/>
            <!-- Controller uses bindconfig to fill the ContentRepository -->
            <class path="net.xyan.controller.ContentAggregationController" obmitConfig="ContentConfiguration,Parameters"/>
            <!-- Controller reacts on missing content and alters the usecase -->
            <class path="net.xyan.controller.ContentUnavailableController" obmitConfig="ContentConfiguration"/>
        </controller>
        <configurations>
	        <configuration type="ContentConfiguration" include="class://de.jamba.config.GlobalBindConfig"/>
	        <configuration type="ContentConfiguration">
	            bind_maincontentbox1 = ...
	        </configuration>
	
	        <configuration type="UIConfiguration" include="class://de.jamba.config.CTypeUIConfig"/>
	        <configuration type="UIConfiguration">
	        	<![CDATA[
	            id_maincontentbox1 = ...
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            id_contentboxXYZ.content = bind_maincontentbox1;
	            ]]>
	        </configuration>
	
	        <configuration type="TemplateConfiguration">
	        	<![CDATA[
	        	root = net.xy.jcms.portal.templates.ExampleMainLayout
				#root.header = de.jamba.frontend.fragments.CatalogHeader
				#root.content = de.jamba.frontend.layouts.NavigationAndSidebar
				#root.content.navigation = de.jamba.frontend.fragments.DefaultNavigation
				#root.content.sidebar = de.jamba.frontend.fragments.GroupPagesSidebar
				#root.content.maincontent = de.jamba.frontend.fragments.TwoContentListsWithTeaser
				#root.footer = de.jamba.frontend.fragments.CatalogFooter
	            ]]>
	        </configuration>
        </configurations>
    </usecase>
</usecases>
